version: "3.5"
services:
  server-php:
    container_name: server-php
    build: "./php"
    volumes:
      - "./php:/server-php"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '2'
  server-go:
    container_name: server-go
    build: "./go"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '2'