version: "3.5"
services:
  app-php:
    container_name: app-php
    build: "./php"
    expose:
      - 9000
    volumes:
      - "app-php-public:/app-php/public"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '2'
    depends_on:
      - app-db
    networks:
      app_network:
  app-go:
    container_name: app-go
    build: "./go"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '2'
    depends_on:
      - app-db
    networks:
      app_network:
  app-db:
    container_name: app-db
    image: postgres:13.15-bookworm
    environment:
      POSTGRES_PASSWORD: server-db-password
    networks:
      app_network:
  app-server:
    container_name: app-nginx
    build: "./nginx"
    volumes:
      - "app-php-public:/app-php/public"
    ports:
      - "80:80"
    networks:
      app_network:

networks:
  app_network:
volumes:
  app-php-public: