security:
    password_hashers:
        #Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'
    providers:
        users:
            memory:
                users:
                    user1: { password: 'user1_pass', roles: ['ROLE_USER'] }
    firewalls:
        main:
            lazy: true
            provider: users
            http_basic:
                realm: server-php
    access_control:
         - { path: /, roles: ROLE_USER }